### ISSUE TITLE
Azure (native)/Java Intro

### ISSUE THREAD

**Issue by jkodroff** [pulumi/workshops#6]
Translate the intro workshop for Azure (create a static website, build a container, deploy container on managed service) into Java.

Review with Mitch, Lee, Laura, Paul.

**Comment by jkodroff** [comment]
Blocked: Not sure how to proceed since `docker.Image` is not available in Java. Waiting for some feedback.

**Comment by aaronkao** [comment]
Is there a reason this wasn't written in YAML first and then generated into all the other languages?
