### ISSUE TITLE
Langchain app does not return service

### ISSUE THREAD

**Issue by awdemos** [pulumi/workshops#87]
### What happened?

When running pulumi up on the langchain app it only generates a 503 Service Temporarily Unavailable error.

### Example

Try it yourself https://github.com/pulumi/workshops/tree/main/develop-intelligent-chat-chatbots-with-langchain-rag-pulumi-aws

### Output of `pulumi about`

I am using the latest version no plugins.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dirien** [comment]
Hey @awdemos,

normally it takes a couple of seconds/minutes until the Fargate instance downloaded the image and started the deployment. 

Have a look into the logs of the Fargate service. In the meantime, I will see if a "wait" would make sense here.

**Comment by dirien** [comment]
Hi @awdemos,

can you check in which AWS region you are deploying and if it is not `eu-central-1` then please change this:

```yaml
awslogs-region: eu-central-1
```

with

```yaml
awslogs-region: ${aws:region}
```

Take care that you set the region with `pulumi config set aws:region`

Let me know if this helped you?
